level: debug
encoders:
  - encoding: json
    outputs:
      - filename: log/app.log
        maxsize: 512
        maxage: 1
        maxbackups: 3
        localtime: true
        compress: false
    config:
      messageKey: M
      levelKey: L
      timeKey: T
      nameKey: N
      callerKey: C
      functionKey: F
      stacktraceKey: S
      levelEncoder: capital
      timeEncoder: RFC3339
      durationEncoder: ms
      callerEncoder: full
      nameEncoder: full
errorOutputs:
  - stderr
  - filename: log/error.log
    maxsize: 512 # megabytes
    maxage: 1 # days
    maxbackups: 3
    localtime: true
    compress: false
